### ISSUE TITLE
feedback-intel-report

### ISSUE THREAD

**Issue by levinhphuc91** [levinhphuc91/vuejs#47]
Desktop
- [x] Padding intel report is not the same with design

- [x] `Intel Intel list The Rise of China` is not align with image below

- [x] Padding of image is smaller than content block on right side.

- [x] Size of interviews is not the same with design

- [x] Caption of video is not the same with design

Responsive

- [x] On iPhone 5 size list of icons is not inline

- [x] List of icons is not center of page

**Comment by nic269** [comment]
Could you check this issue after merged at: https://github.com/levinhphuc91/vuejs/pull/49
